# Generated by Django 3.1.7 on 2021-03-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('review', models.TextField(default='none')),
                ('rating', models.FloatField()),
            ],
        ),
    ]
