# Generated by Django 3.1.7 on 2021-03-28 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArticles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='rating',
            new_name='Rating',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='review',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='title',
        ),
        migrations.AddField(
            model_name='articles',
            name='Author',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='RatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='Review',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='articles',
            name='Title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
