# Generated by Django 3.1.7 on 2021-03-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArticles', '0002_auto_20210327_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='RatedDate',
            new_name='ratedDate',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Review',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Title',
            new_name='title',
        ),
    ]
