# Generated by Django 3.1.7 on 2021-03-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArticles', '0003_auto_20210328_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='Review',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='ratedDate',
        ),
        migrations.AddField(
            model_name='articlesrating',
            name='ArticlesTitle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NewsArticles.articles'),
            preserve_default=False,
        ),
    ]
