# Generated by Django 3.1.7 on 2021-03-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArticles', '0002_auto_20210327_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratedDate', models.DateTimeField()),
                ('ReviewTitle', models.CharField(max_length=100)),
                ('review', models.TextField(default='Write you review here')),
            ],
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='RatedDate',
            new_name='ratedDate',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='articles',
            name='Review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsArticles.articlesrating'),
        ),
    ]
