# Generated by Django 3.1.7 on 2021-03-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArticles', '0004_auto_20210328_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='rating',
        ),
        migrations.AddField(
            model_name='articles',
            name='url',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlesrating',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
