# Generated by Django 3.1.7 on 2021-03-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20210327_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='qualification',
        ),
        migrations.AddField(
            model_name='profiles',
            name='qualification',
            field=models.ManyToManyField(blank=True, to='Profiles.UserQualifications'),
        ),
    ]
