# Generated by Django 3.1.7 on 2021-03-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_auto_20210328_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
